export const CATEGORIES = [
  {
    id: "public-service",
    label: "Public service",
    blurb: "Ministries, districts, commissions, and statutory bodies.",
    template: "official" as const,
    skills: "Policy drafting, stakeholder engagement, procurement, reporting, PFMA",
    extras: ["Languages", "Computer packages"],
  },
  {
    id: "ngo",
    label: "NGO & development",
    blurb: "INGOs, CSOs, and donor-funded programmes.",
    template: "official" as const,
    skills: "MEAL, proposal writing, safeguarding, community mobilisation, donor reporting",
    extras: ["Languages", "Referees available"],
  },
  {
    id: "banking",
    label: "Banking & microfinance",
    blurb: "Commercial banks, SACCOs, and MFIs.",
    template: "editorial" as const,
    skills: "Credit analysis, KYC, Excel, customer service, risk",
    extras: ["Certifications"],
  },
  {
    id: "education",
    label: "Education & teaching",
    blurb: "Schools, universities, and TVET.",
    template: "official" as const,
    skills: "Lesson planning, UNEB, classroom management, ICT in education",
    extras: ["Registration", "Languages"],
  },
  {
    id: "health",
    label: "Healthcare",
    blurb: "Hospitals, clinics, public health, and pharmacies.",
    template: "official" as const,
    skills: "Clinical care, HMIS, counselling, infection prevention",
    extras: ["Licence", "Languages"],
  },
  {
    id: "ict",
    label: "ICT & software",
    blurb: "Product, engineering, support, and telecoms.",
    template: "editorial" as const,
    skills: "TypeScript, SQL, cloud, support tickets, networks",
    extras: ["GitHub", "Certifications"],
  },
  {
    id: "engineering",
    label: "Engineering & construction",
    blurb: "Civil, electrical, oil & gas support, and sites.",
    template: "compact" as const,
    skills: "AutoCAD, site supervision, HSE, BOQ, contract admin",
    extras: ["ERB / UIPE"],
  },
  {
    id: "agriculture",
    label: "Agriculture & agribusiness",
    blurb: "Extension, agronomy, cooperatives, and processing.",
    template: "official" as const,
    skills: "Extension, value chains, farmer training, records",
    extras: ["Languages"],
  },
  {
    id: "hospitality",
    label: "Hospitality & tourism",
    blurb: "Hotels, lodges, airlines, and events.",
    template: "modern" as const,
    skills: "Front office, F&B, guest relations, Opera / Fidelio",
    extras: ["Languages"],
  },
  {
    id: "legal",
    label: "Legal & compliance",
    blurb: "Chambers, in-house, and company secretarial.",
    template: "executive" as const,
    skills: "Legal research, drafting, litigation support, compliance",
    extras: ["Enrolment"],
  },
  {
    id: "sales",
    label: "Sales, retail & FMCG",
    blurb: "Field sales, merchandising, and trade.",
    template: "compact" as const,
    skills: "Route to market, negotiation, CRM, merchandising",
    extras: ["Languages"],
  },
  {
    id: "graduate",
    label: "Fresh graduate",
    blurb: "First role, internship, or national service.",
    template: "official" as const,
    skills: "Microsoft Office, research, teamwork, communication",
    extras: ["Languages", "Interests"],
  },
  {
    id: "oil-gas",
    label: "Oil, gas & mining",
    blurb: "Albertine, Karamoja, and contractor roles.",
    template: "compact" as const,
    skills: "HSE, logistics, community liaison, reporting",
    extras: ["Certifications"],
  },
  {
    id: "logistics",
    label: "Transport & logistics",
    blurb: "Freight, clearing, and last-mile.",
    template: "compact" as const,
    skills: "Clearing & forwarding, fleet, warehousing, ASYCUDA",
    extras: ["Licence"],
  },
  {
    id: "media",
    label: "Media & communications",
    blurb: "Newsrooms, brand, and digital.",
    template: "modern" as const,
    skills: "Writing, social, Adobe, media relations, Luganda / English",
    extras: ["Portfolio"],
  },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export function categoryById(id: string) {
  return CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[0];
}
